require('./eslint-base.test')
require('./eslint-vue.test')
require('./prettier-base.test')
require('./prettier-css.test')
require('./prettier-vue.test')

require('./stylelint-base.test')
require('./stylelint-scss.test')
require('./stylelint-bem-pattern.test')
require('./stylelint-order.test')
